services:

  app:
    container_name: backend-app
    build: ./backend
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: [ "sh", "-c", "./bin/migrate up && ./bin/api" ]

  db:
    container_name: backend-db
    image: postgres:alpine
    env_file: .env
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${DB_USER} -d ${DB_NAME}'"]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
