services:

  app:
    container_name: backend-app
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    container_name: backend-db
    image: postgres:alpine
    environment:
      - POSTGRES_DB=api_db
      - POSTGRES_USER=api_user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    restart: always
