basePath: /v1
definitions:
  datatype.DTO:
    properties:
      field_name:
        type: string
      id:
        type: string
    type: object
  datatype.DataType:
    properties:
      field_name:
        type: string
    type: object
  err.Error:
    properties:
      error:
        type: string
    type: object
  err.Errors:
    properties:
      errors:
        items:
          type: string
        type: array
    type: object
host: localhost:8080
info:
  contact:
    name: Lucas Bagatini
    url: lalilulelo
  description: This is an api for a digital storefront. Part of meli test.
  title: MELI STORE API
  version: "1.0"
paths:
  /DataType:
    get:
      consumes:
      - application/json
      description: Read all DataType
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/datatype.DTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Read all DataType
      tags:
      - DataType
    post:
      consumes:
      - application/json
      description: Create DataType
      parameters:
      - description: Book form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/datatype.DataType'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/err.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Create DataType
      tags:
      - DataType
  /DataType/{id}:
    delete:
      consumes:
      - application/json
      description: Delete DataType
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Delete DataType
      tags:
      - DataType
    get:
      consumes:
      - application/json
      description: Read DataType by id
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/datatype.DTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Read DataType by id
      tags:
      - DataType
    put:
      consumes:
      - application/json
      description: Update DataType
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      - description: Book form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/datatype.DataType'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/err.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Update DataType
      tags:
      - DataType
swagger: "2.0"
