// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package repositories

import (
	"github.com/google/uuid"
)

type Cart struct {
	ID         uuid.UUID `json:"id"`
	ProductID  uuid.UUID `json:"product_id"`
	CustomerID uuid.UUID `json:"customer_id"`
	Amount     int32     `json:"amount"`
}

type Customer struct {
	ID    uuid.UUID `json:"id"`
	Login string    `json:"login"`
	Name  string    `json:"name"`
}

type Product struct {
	ID      uuid.UUID `json:"id"`
	Barcode string    `json:"barcode"`
	Name    string    `json:"name"`
	Price   int32     `json:"price"`
	Stock   int32     `json:"stock"`
}
