// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: product.sql

package repositories

import (
	"context"

	"github.com/google/uuid"
)

const CreateProduct = `-- name: CreateProduct :one
INSERT INTO product (
    id, barcode, name, price, stock
) VALUES (
    uuid_generate_v4(), $1, $2, $3, $4
)
    RETURNING id, barcode, name, price, stock
`

type CreateProductParams struct {
	Barcode string `json:"barcode"`
	Name    string `json:"name"`
	Price   int32  `json:"price"`
	Stock   int32  `json:"stock"`
}

// create
//
//	INSERT INTO product (
//	    id, barcode, name, price, stock
//	) VALUES (
//	    uuid_generate_v4(), $1, $2, $3, $4
//	)
//	    RETURNING id, barcode, name, price, stock
func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, CreateProduct,
		arg.Barcode,
		arg.Name,
		arg.Price,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Stock,
	)
	return i, err
}

const DeleteProduct = `-- name: DeleteProduct :exec
DELETE FROM product
    WHERE
        id = $1
`

// delete
//
//	DELETE FROM product
//	    WHERE
//	        id = $1
func (q *Queries) DeleteProduct(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, DeleteProduct, id)
	return err
}

const ReadByProductId = `-- name: ReadByProductId :one
SELECT id, barcode, name, price, stock FROM product
    WHERE
        id = $1
    LIMIT 1
`

// read one
//
//	SELECT id, barcode, name, price, stock FROM product
//	    WHERE
//	        id = $1
//	    LIMIT 1
func (q *Queries) ReadByProductId(ctx context.Context, id uuid.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, ReadByProductId, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Stock,
	)
	return i, err
}

const ReadProduct = `-- name: ReadProduct :many
SELECT id, barcode, name, price, stock FROM product
    ORDER BY name
`

// read many
//
//	SELECT id, barcode, name, price, stock FROM product
//	    ORDER BY name
func (q *Queries) ReadProduct(ctx context.Context) ([]Product, error) {
	rows, err := q.db.Query(ctx, ReadProduct)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Product{}
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Barcode,
			&i.Name,
			&i.Price,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const UpdateProduct = `-- name: UpdateProduct :one
UPDATE product
SET
    barcode = $2,
	name = $3,
	price = $4,
	stock = $5

    WHERE
        id = $1
    RETURNING id, barcode, name, price, stock
`

type UpdateProductParams struct {
	ID      uuid.UUID `json:"id"`
	Barcode string    `json:"barcode"`
	Name    string    `json:"name"`
	Price   int32     `json:"price"`
	Stock   int32     `json:"stock"`
}

// update
//
//	UPDATE product
//	SET
//	    barcode = $2,
//		name = $3,
//		price = $4,
//		stock = $5
//
//	    WHERE
//	        id = $1
//	    RETURNING id, barcode, name, price, stock
func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, UpdateProduct,
		arg.ID,
		arg.Barcode,
		arg.Name,
		arg.Price,
		arg.Stock,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Barcode,
		&i.Name,
		&i.Price,
		&i.Stock,
	)
	return i, err
}
